sudo: required

before_install: make -f travis/Makefile prepare_environment

osx_image: xcode12.2

os:
  - linux
  - osx

language: cpp
compiler:
  - gcc
  - clang

matrix:
  allow_failures:
    - os: osx

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "WG/iday4nudNJ9acP/gjjuXzI0Jw0MN0zP9JA3WueMvMV0UrVRnBKM+papB06XiB4Gyiaoy92pfOGzmby0ciMAvydBn2DyuGZhM1nXuEIbkQqfP3AR3z6nCZHY27NAhVnpnEAyb56FwD353JMVZj34cnRmcjgKArMM3Y8W66Zls="

script: make -f travis/Makefile run-tests

after_success:
  - bash <(curl -s https://codecov.io/bash) -s /tmp/kcov

notifications:
  recipients:
    - simon.kagstrom@gmail.com
  email:
    on_success: change
    on_failure: always
